### PR TITLE
Added driver source

### PR DESCRIPTION
**Pull request by ACCakut**

### CODE REVIEW

**Comment by markrossington** [comment]
Appreciate the documentation. Just to check, why do you need this?

**Comment by ACCakut** [comment]
When trying to run dfu-util on a quite fresh Windows (not much microcontroller stuff done on it before) it complained about not finding a suitable USB device. The device manager showed up the ST bootloader with missing drivers. So I followed the instructions from Artillery and Freakydude that supposed me to install this software which brings drivers along.

It is definitely more bloat than just the drivers needed, but it worked for me and is an authentic source for the driver files.

**Comment by markrossington** [comment]
Appreciate the response. I see it must be the serial drivers which I believe are FTDI ones. Until I find a better (official) source then yes we should include this link here. 

I hope you don't mind I will reword it a little to make that clear the merge. Thanks again for your submission.

**Comment by markrossington** [comment]
Ok done, going to merge

**Pull request merged**
